baseURL: https://realjackyli.github.io/ # 绑定的域名
languageCode: zh-cn
title: MissOrange
theme: hugo-PaperMod  # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics:  # 谷歌统计
# Copyright: Sulv

paginate: 15    # 首页每页显示的文章数
summaryLength: 70 # 文章概览的自字数，默认70

minify:
  disableXML: true
  # minifyOutput: true

permalinks: # 访问博客时网址的显示形式
  post: "/:year/:month/:day/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: zh # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

menu:
  main:
    - identifier: search
      name: 🔍 搜索
      url: search
      weight: 1
    - identifier: home
      name: 🏠 主页
      url: /
      weight: 2
    - identifier: posts
      name: 📚 文章
      url: posts
      weight: 3
    - identifier: archives
      name: ⏱️ 时间轴
      url: archives/
      weight: 40
    - identifier: toys
      name: 🧸 小玩具
      url: toys
      weight: 50
    - identifier: message
      name: 💬 留言板
      url: message
      weight: 60
    - identifier: about
      name: 🙋🏻‍♂️ 关于
      url: about
      weight: 70
    
outputs:
  home:
    - HTML
    - RSS
    - JSON

# 这里的参数会被代码以 .Site.Params 的形式读取
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author: Sulv
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto  # defaultTheme: light or  dark
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # 隐藏页脚
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #显示文章更新时间

  ShowToc: true # 显示目录
  TocOpen: true # 自动展开目录

  extendCodeBackground: false # 代码块是否自动横向展开

  comments: true

  profileMode:
    enabled: true
    title: Hi! My Name Is Orange!
    subtitle: "『拥有橘子女仆的力量 ，我是无敌的！』"
    imageUrl: "img/orange.jpg"
    imageTitle:
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: 👨🏻‍💻 技术
        url: posts/tech
      - name: 🎮 评测
        url: posts/read
      - name: 🗣 瞎78聊
        url: posts/life

  socialIcons:
    - name: github
      url: "https://github.com/realjackyli"
    - name: twitter
      url: "https://twitter.com/realjackyli"
    - name: twitch
      url: "https://www.twitch.tv/realjackyli"
    - name: bilibili
      url: "https://space.bilibili.com/340384184"
    - name: steam
      url: "https://steamcommunity.com/id/realjackyli/"
    - name: RSS
      url: "index.xml"

  label: # 左上角图标
    text: "MissOrange's Blog"
    icon: "img/head.jpg"
    iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: ""

  assets:
    favicon: "img/orange.jpg"
    favicon16x16: "img/orange.jpg"
    favicon32x32: "img/orange.jpg"
    apple_touch_icon: "img/orange.jpg"
    safari_pinned_tab: "img/orange.jpg"
    disableFingerprinting: true # 禁用指纹

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  fuseOpts: # 搜索配置
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary" ]

  StartYear: 2024 # 底部开始年份
  # FilingNo: 填写自己的备案号 # 底部备案号
  # PublicSecurityIconLink: 填自己的公安图标链接 # 填自己的公安图标链接,可用绝对路径，相对路径如 img/beian.png
  # PublicNetworkSecurity: 填自己的公网安备 # 底部公网安备号

  Reward: false #打赏是否开启
  # 打赏微信图片地址，
  # 可用绝对和相对地址，相对地址的图片需放在static/img下，
  # 填写格式为img/wechat_pay.png
  WechatPay: img/wechat_pay.png
  Alipay: img/alipay.png #打赏支付宝图片地址

  # twikoo评论
  twikoo:
    version: 1.5.8 # 填写twikoo版本号
    id: https://realjackyli-twikoo.hf.space # 填写自己的twikoo id
    region:  # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数，请看twikoo官方文档

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    noClasses: true
    tabWidth: 4
    style: monokai
    # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
    # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
    # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
    # lineNoStart：行号从编号几开始，一般从 1 开始。
    # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
    # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
    # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
        
